name: Deploy
on:
  push: {}
  workflow_dispatch: {}

env:
  IMAGE: ghcr.io/$GITHUB_REPOSITORY/$(basename $PWD)/prod

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: docker login ghcr.io -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build
        run: docker build -f dev/build/Dockerfile -t ${{ env.IMAGE }}:latest .
      - name: Push
        run: docker push ${{ env.IMAGE }}:latest

      - uses: rollun-com/actions/update-d2c-service@master
        with:
          service-name: wiki
          d2c-email: ${{ secrets.D2C_USER }}
          d2c-password: ${{ secrets.D2C_PASSWORD }}
